### ISSUE TITLE
Use @scoped package for npmjs

### ISSUE THREAD

**Issue by rafaels-dev** [devopness/sdk-js#19]
Npmjs supports scoped packages like @devopness/devopness-sdk-js. This enforces your brand and allow you to expand to private repositories easily when it would be required.

Suggestion: create a private free organization in Npm and publish this package again.

**Comment by jfoliveira** [comment]
Great suggestion!

1. Marked [original package](https://www.npmjs.com/package/devopness-sdk-js) as deprecated
